const CONSTANTES = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLECERSESION: 'ESTABLECERSESION',
  CERRARSESION: 'CERRARSESION',
  LIMPIAR_IMAGEN_SIGNUP: 'LIMPIAR_IMAGEN_SIGNUP',
  CARGAR_IMAGEN_SIGNUP: 'CARGAR_IMAGEN_SIGNUP',
  CLOUDINARY_NAME: ' https://api.cloudinary.com/v1_1/ddjm9hedk/image/upload',
  CLOUDINARY_PRESET: 'datv2djh',
};


export default CONSTANTES;
